# Generated by Django 5.0.2 on 2024-02-29 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_regi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 2, 29, 11, 35, 20, 372575, tzinfo=datetime.timezone.utc
                ),
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_name",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 2, 29, 11, 35, 31, 79885, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_contact",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterModelTable(
            name="employee",
            table=None,
        ),
    ]
